image: debian:bookworm

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apt-get update
  - DEBIAN_FRONTEND=noninteractive apt-get install -qqy
        clang-format
        clang-tidy
        cmake
        g++
        git
        libglew-dev
        libglfw3-dev
        libopencv-dev
        libopengl-dev
        make

stages:
  - lint
  - export-test

format:
  stage: lint
  script:
    - mkdir build && cd build
    - cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
    - make format
    - test -z $(git diff) && exit 0 || exit 1

example-build:
  stage: export-test
  script:
    - mkdir build && cd build
    - cmake ..
    - make && make install
    - cd ../tests/example-build
    - cp ../../src/app-example.cpp ./
    - cp ../../src/farshow-client.cpp ./
    - mkdir build && cd build
    - cmake ..
    - make
