image: debian:bookworm

variables:
  GIT_SUBMODULE_STRATEGY: recursive

.ace: &ace
    tags: ['ace-x86_64']

before_script:
  - apt-get update
  - DEBIAN_FRONTEND=noninteractive apt-get install -qqy
        clang-format
        clang-tidy
        cmake
        g++
        git
        libglew-dev
        libglfw3-dev
        libopencv-dev
        libopengl-dev
        python3-dev
        python3-pybind11
        pybind11-dev
        make

format:
  <<: *ace
  script:
    - mkdir build && cd build
    - cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
    - make format
    - test -z $(git diff) && exit 0 || exit 1

build:
  <<: *ace
  script:
    - mkdir build && cd build
    - cmake ..
    - make -j`nproc`

example-build:
  <<: *ace
  script:
    - mkdir build && cd build
    - cmake ..
    - make -j`nproc` && make install
    - cd ../tests/example-build
    - cp ../../src/app-example.cpp ./
    - cp ../../src/farshow-client.cpp ./
    - mkdir build && cd build
    - cmake ..
    - make -j`nproc`
